### ISSUE TITLE
latest flycheck-hledger sometimes hangs

### ISSUE THREAD

**Issue by simonmichael** [DamienCassou/flycheck-hledger#25]
Since #22's commit 53645a6, with hledger 1.33 in PATH and ordereddates in `flycheck-hledger-checks`, I see flycheck-hledger hanging when I move or uncomment entries to trigger an ordereddates failure. (To regain control of Emacs, you must wait a bit then press control-g a few times.)

**Comment by DamienCassou** [comment]
@shivjm: could you please have a look?

**Comment by shivjm** [comment]
Thanks for the report, Simon. Do you think you could suggest some steps to reproduce it? This is what I tried:
1. Open an existing journal.
2. Cut the last entry.
3. Paste it a few transactions earlier so that it’s now out of order.

I haven’t seen it hanging so far.

**Comment by simonmichael** [comment]
I just tried this again and haven't been able to reproduce yet @shivjm. I'll close if it doesn't reappear soon.

**Comment by DamienCassou** [comment]
I'm closing. Feel free to reopen if you get it again.
